name: seven_icon
description: "Seven Icon: pacote de ícones do AtletaDoVolei exportados como icon font."
version: 0.11.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=3.18.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: SevenIcon
      fonts:
        - asset: assets/fonts/icons.ttf
